name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.5
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    
    - name: Upload unsigned APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-unsigned
        path: app/build/outputs/apk/release/app-release-unsigned.apk
    
    # Optional: Sign the APK if keystore is provided as a secret
    - name: Sign APK
      if: ${{ env.SIGNING_KEY_BASE64 != '' }}
      run: |
        echo ${{ secrets.SIGNING_KEY_BASE64 }} | base64 -d > keystore.jks
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks \
                  -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} \
                  app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}
        
        # Verify the signature
        jarsigner -verify -verbose -certs app/build/outputs/apk/release/app-release-unsigned.apk
        
        # Rename the signed APK
        mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-signed.apk
      env:
        SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
    
    # Upload signed APK if it was signed
    - name: Upload signed APK
      if: ${{ env.SIGNING_KEY_BASE64 != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: app-release-signed
        path: app/build/outputs/apk/release/app-release-signed.apk
      env:
        SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}

# To use the signing step, add these secrets to your GitHub repository:
# SIGNING_KEY_BASE64: Base64-encoded keystore file (run: base64 keystore.jks)
# KEYSTORE_PASSWORD: Password for the keystore
# KEY_PASSWORD: Password for the key
# KEY_ALIAS: Alias of the key
